import type { Metadata } from 'next'
import SiteHeader from '@/components/layout/SiteHeader'
import { supabaseServer } from '@/lib/supabase/server'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = await supabaseServer()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  let role: 'student' | 'employer' | undefined
  if (user) {
    const { data: userRow } = await supabase.from('users').select('role').eq('id', user.id).maybeSingle()
    if (userRow?.role === 'student' || userRow?.role === 'employer') {
      role = userRow.role
    }
  }

  return (
    <html lang="en">
      <body className="antialiased">
        <SiteHeader isAuthenticated={Boolean(user)} role={role} />
        {children}
      </body>
    </html>
  )
}
