export type StateOption = {
  code: string
  name: string
}

export type CityOption = {
  city: string
  state: string
}

export const US_STATE_OPTIONS: readonly StateOption[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'District of Columbia' },
] as const

export const US_CITY_OPTIONS: readonly CityOption[] = [
  { city: 'Birmingham', state: 'AL' },
  { city: 'Montgomery', state: 'AL' },
  { city: 'Anchorage', state: 'AK' },
  { city: 'Phoenix', state: 'AZ' },
  { city: 'Tucson', state: 'AZ' },
  { city: 'Little Rock', state: 'AR' },
  { city: 'Los Angeles', state: 'CA' },
  { city: 'San Diego', state: 'CA' },
  { city: 'San Francisco', state: 'CA' },
  { city: 'San Jose', state: 'CA' },
  { city: 'Sacramento', state: 'CA' },
  { city: 'Denver', state: 'CO' },
  { city: 'Colorado Springs', state: 'CO' },
  { city: 'Hartford', state: 'CT' },
  { city: 'Bridgeport', state: 'CT' },
  { city: 'Wilmington', state: 'DE' },
  { city: 'Washington', state: 'DC' },
  { city: 'Miami', state: 'FL' },
  { city: 'Orlando', state: 'FL' },
  { city: 'Tampa', state: 'FL' },
  { city: 'Jacksonville', state: 'FL' },
  { city: 'Atlanta', state: 'GA' },
  { city: 'Savannah', state: 'GA' },
  { city: 'Honolulu', state: 'HI' },
  { city: 'Boise', state: 'ID' },
  { city: 'Chicago', state: 'IL' },
  { city: 'Springfield', state: 'IL' },
  { city: 'Indianapolis', state: 'IN' },
  { city: 'Fort Wayne', state: 'IN' },
  { city: 'Des Moines', state: 'IA' },
  { city: 'Wichita', state: 'KS' },
  { city: 'Topeka', state: 'KS' },
  { city: 'Louisville', state: 'KY' },
  { city: 'Lexington', state: 'KY' },
  { city: 'New Orleans', state: 'LA' },
  { city: 'Baton Rouge', state: 'LA' },
  { city: 'Portland', state: 'ME' },
  { city: 'Baltimore', state: 'MD' },
  { city: 'Annapolis', state: 'MD' },
  { city: 'Boston', state: 'MA' },
  { city: 'Worcester', state: 'MA' },
  { city: 'Detroit', state: 'MI' },
  { city: 'Grand Rapids', state: 'MI' },
  { city: 'Minneapolis', state: 'MN' },
  { city: 'St. Paul', state: 'MN' },
  { city: 'Jackson', state: 'MS' },
  { city: 'Kansas City', state: 'MO' },
  { city: 'St. Louis', state: 'MO' },
  { city: 'Jefferson City', state: 'MO' },
  { city: 'Billings', state: 'MT' },
  { city: 'Helena', state: 'MT' },
  { city: 'Omaha', state: 'NE' },
  { city: 'Lincoln', state: 'NE' },
  { city: 'Las Vegas', state: 'NV' },
  { city: 'Reno', state: 'NV' },
  { city: 'Concord', state: 'NH' },
  { city: 'Manchester', state: 'NH' },
  { city: 'Newark', state: 'NJ' },
  { city: 'Jersey City', state: 'NJ' },
  { city: 'Trenton', state: 'NJ' },
  { city: 'Albuquerque', state: 'NM' },
  { city: 'Santa Fe', state: 'NM' },
  { city: 'New York', state: 'NY' },
  { city: 'Buffalo', state: 'NY' },
  { city: 'Rochester', state: 'NY' },
  { city: 'Albany', state: 'NY' },
  { city: 'Charlotte', state: 'NC' },
  { city: 'Raleigh', state: 'NC' },
  { city: 'Durham', state: 'NC' },
  { city: 'Fargo', state: 'ND' },
  { city: 'Bismarck', state: 'ND' },
  { city: 'Columbus', state: 'OH' },
  { city: 'Cleveland', state: 'OH' },
  { city: 'Cincinnati', state: 'OH' },
  { city: 'Oklahoma City', state: 'OK' },
  { city: 'Tulsa', state: 'OK' },
  { city: 'Portland', state: 'OR' },
  { city: 'Salem', state: 'OR' },
  { city: 'Philadelphia', state: 'PA' },
  { city: 'Pittsburgh', state: 'PA' },
  { city: 'Harrisburg', state: 'PA' },
  { city: 'Providence', state: 'RI' },
  { city: 'Charleston', state: 'SC' },
  { city: 'Columbia', state: 'SC' },
  { city: 'Sioux Falls', state: 'SD' },
  { city: 'Pierre', state: 'SD' },
  { city: 'Nashville', state: 'TN' },
  { city: 'Memphis', state: 'TN' },
  { city: 'Austin', state: 'TX' },
  { city: 'Dallas', state: 'TX' },
  { city: 'Houston', state: 'TX' },
  { city: 'San Antonio', state: 'TX' },
  { city: 'Salt Lake City', state: 'UT' },
  { city: 'West Jordan', state: 'UT' },
  { city: 'West Valley City', state: 'UT' },
  { city: 'Draper', state: 'UT' },
  { city: 'Lehi', state: 'UT' },
  { city: 'Orem', state: 'UT' },
  { city: 'Logan', state: 'UT' },
  { city: 'Sandy', state: 'UT' },
  { city: 'Bountiful', state: 'UT' },
  { city: 'Provo', state: 'UT' },
  { city: 'Ogden', state: 'UT' },
  { city: 'Burlington', state: 'VT' },
  { city: 'Montpelier', state: 'VT' },
  { city: 'Richmond', state: 'VA' },
  { city: 'Virginia Beach', state: 'VA' },
  { city: 'Arlington', state: 'VA' },
  { city: 'Seattle', state: 'WA' },
  { city: 'Spokane', state: 'WA' },
  { city: 'Tacoma', state: 'WA' },
  { city: 'Charleston', state: 'WV' },
  { city: 'Milwaukee', state: 'WI' },
  { city: 'Madison', state: 'WI' },
  { city: 'Cheyenne', state: 'WY' },
] as const

const STATE_CODE_SET = new Set(US_STATE_OPTIONS.map((state) => state.code))

export function normalizeStateCode(value: string | null | undefined) {
  const normalized = (value ?? '').trim().toUpperCase()
  return STATE_CODE_SET.has(normalized) ? normalized : ''
}

export function isVerifiedStateCode(value: string | null | undefined) {
  return normalizeStateCode(value).length > 0
}

export function isVerifiedCityForState(city: string | null | undefined, state: string | null | undefined) {
  const normalizedCity = (city ?? '').trim()
  const normalizedState = normalizeStateCode(state)
  if (!normalizedCity || !normalizedState) return false
  return US_CITY_OPTIONS.some((option) => option.city === normalizedCity && option.state === normalizedState)
}
