-- Expanded canonical skills catalog with categories and aliases.
-- Generated skill count: 265; alias count: 691.

insert into public.canonical_skill_categories (slug, name)
values
  ('business', 'Business'),
  ('finance', 'Finance'),
  ('data', 'Data'),
  ('software', 'Software'),
  ('cloud', 'Cloud'),
  ('marketing', 'Marketing'),
  ('operations', 'Operations'),
  ('sales', 'Sales'),
  ('design', 'Design'),
  ('healthcare', 'Healthcare'),
  ('construction', 'Construction'),
  ('hospitality', 'Hospitality'),
  ('professional', 'Professional')
on conflict do nothing;

with incoming(slug, label, category_name, normalized_name) as (
  values
    ('microsoft-excel', 'Microsoft Excel', 'Business', 'microsoftexcel'),
    ('microsoft-powerpoint', 'Microsoft PowerPoint', 'Business', 'microsoftpowerpoint'),
    ('microsoft-word', 'Microsoft Word', 'Business', 'microsoftword'),
    ('business-writing', 'Business Writing', 'Business', 'businesswriting'),
    ('business-communication', 'Business Communication', 'Business', 'businesscommunication'),
    ('stakeholder-management', 'Stakeholder Management', 'Business', 'stakeholdermanagement'),
    ('project-coordination', 'Project Coordination', 'Business', 'projectcoordination'),
    ('strategic-planning', 'Strategic Planning', 'Business', 'strategicplanning'),
    ('business-analysis', 'Business Analysis', 'Business', 'businessanalysis'),
    ('requirements-gathering', 'Requirements Gathering', 'Business', 'requirementsgathering'),
    ('process-documentation', 'Process Documentation', 'Business', 'processdocumentation'),
    ('change-management', 'Change Management', 'Business', 'changemanagement'),
    ('client-relations', 'Client Relations', 'Business', 'clientrelations'),
    ('vendor-management', 'Vendor Management', 'Business', 'vendormanagement'),
    ('negotiation', 'Negotiation', 'Business', 'negotiation'),
    ('meeting-facilitation', 'Meeting Facilitation', 'Business', 'meetingfacilitation'),
    ('presentation-skills', 'Presentation Skills', 'Business', 'presentationskills'),
    ('public-speaking', 'Public Speaking', 'Business', 'publicspeaking'),
    ('time-management', 'Time Management', 'Business', 'timemanagement'),
    ('cross-functional-collaboration', 'Cross-functional Collaboration', 'Business', 'crossfunctionalcollaboration'),
    ('decision-making', 'Decision Making', 'Business', 'decisionmaking'),
    ('problem-solving', 'Problem Solving', 'Business', 'problemsolving'),
    ('professional-etiquette', 'Professional Etiquette', 'Business', 'professionaletiquette'),
    ('financial-modeling', 'Financial Modeling', 'Finance', 'financialmodeling'),
    ('valuation', 'Valuation', 'Finance', 'valuation'),
    ('financial-statement-analysis', 'Financial Statement Analysis', 'Finance', 'financialstatementanalysis'),
    ('gaap', 'GAAP', 'Finance', 'gaap'),
    ('budgeting', 'Budgeting', 'Finance', 'budgeting'),
    ('forecasting', 'Forecasting', 'Finance', 'forecasting'),
    ('variance-analysis', 'Variance Analysis', 'Finance', 'varianceanalysis'),
    ('cash-flow-analysis', 'Cash Flow Analysis', 'Finance', 'cashflowanalysis'),
    ('corporate-finance', 'Corporate Finance', 'Finance', 'corporatefinance'),
    ('investment-analysis', 'Investment Analysis', 'Finance', 'investmentanalysis'),
    ('equity-research', 'Equity Research', 'Finance', 'equityresearch'),
    ('credit-analysis', 'Credit Analysis', 'Finance', 'creditanalysis'),
    ('mergers-and-acquisitions', 'Mergers and Acquisitions', 'Finance', 'mergersandacquisitions'),
    ('due-diligence', 'Due Diligence', 'Finance', 'duediligence'),
    ('capital-markets', 'Capital Markets', 'Finance', 'capitalmarkets'),
    ('portfolio-analysis', 'Portfolio Analysis', 'Finance', 'portfolioanalysis'),
    ('risk-management', 'Risk Management', 'Finance', 'riskmanagement'),
    ('treasury-operations', 'Treasury Operations', 'Finance', 'treasuryoperations'),
    ('quickbooks', 'QuickBooks', 'Finance', 'quickbooks'),
    ('accounts-payable', 'Accounts Payable', 'Finance', 'accountspayable'),
    ('accounts-receivable', 'Accounts Receivable', 'Finance', 'accountsreceivable'),
    ('reconciliations', 'Reconciliations', 'Finance', 'reconciliations'),
    ('audit-support', 'Audit Support', 'Finance', 'auditsupport'),
    ('tax-preparation', 'Tax Preparation', 'Finance', 'taxpreparation'),
    ('payroll-processing', 'Payroll Processing', 'Finance', 'payrollprocessing'),
    ('internal-controls', 'Internal Controls', 'Finance', 'internalcontrols'),
    ('cost-accounting', 'Cost Accounting', 'Finance', 'costaccounting'),
    ('managerial-accounting', 'Managerial Accounting', 'Finance', 'managerialaccounting'),
    ('fund-accounting', 'Fund Accounting', 'Finance', 'fundaccounting'),
    ('revenue-recognition', 'Revenue Recognition', 'Finance', 'revenuerecognition'),
    ('sql', 'SQL', 'Data', 'sql'),
    ('postgresql', 'PostgreSQL', 'Data', 'postgresql'),
    ('mysql', 'MySQL', 'Data', 'mysql'),
    ('sqlite', 'SQLite', 'Data', 'sqlite'),
    ('data-cleaning', 'Data Cleaning', 'Data', 'datacleaning'),
    ('data-wrangling', 'Data Wrangling', 'Data', 'datawrangling'),
    ('exploratory-data-analysis', 'Exploratory Data Analysis', 'Data', 'exploratorydataanalysis'),
    ('statistical-analysis', 'Statistical Analysis', 'Data', 'statisticalanalysis'),
    ('a-b-testing', 'A/B Testing', 'Data', 'abtesting'),
    ('hypothesis-testing', 'Hypothesis Testing', 'Data', 'hypothesistesting'),
    ('regression-analysis', 'Regression Analysis', 'Data', 'regressionanalysis'),
    ('data-visualization', 'Data Visualization', 'Data', 'datavisualization'),
    ('dashboarding', 'Dashboarding', 'Data', 'dashboarding'),
    ('tableau', 'Tableau', 'Data', 'tableau'),
    ('power-bi', 'Power BI', 'Data', 'powerbi'),
    ('looker-studio', 'Looker Studio', 'Data', 'lookerstudio'),
    ('excel-pivot-tables', 'Excel Pivot Tables', 'Data', 'excelpivottables'),
    ('excel-xlookup', 'Excel XLOOKUP', 'Data', 'excelxlookup'),
    ('excel-vlookup', 'Excel VLOOKUP', 'Data', 'excelvlookup'),
    ('google-sheets', 'Google Sheets', 'Data', 'googlesheets'),
    ('python-for-analytics', 'Python for Analytics', 'Data', 'pythonforanalytics'),
    ('r-programming', 'R Programming', 'Data', 'rprogramming'),
    ('jupyter', 'Jupyter', 'Data', 'jupyter'),
    ('pandas', 'Pandas', 'Data', 'pandas'),
    ('numpy', 'NumPy', 'Data', 'numpy'),
    ('etl', 'ETL', 'Data', 'etl'),
    ('data-modeling', 'Data Modeling', 'Data', 'datamodeling'),
    ('data-governance', 'Data Governance', 'Data', 'datagovernance'),
    ('data-quality', 'Data Quality', 'Data', 'dataquality'),
    ('business-intelligence', 'Business Intelligence', 'Data', 'businessintelligence'),
    ('javascript', 'JavaScript', 'Software', 'javascript'),
    ('typescript', 'TypeScript', 'Software', 'typescript'),
    ('react', 'React', 'Software', 'react'),
    ('next-js', 'Next.js', 'Software', 'nextjs'),
    ('node-js', 'Node.js', 'Software', 'nodejs'),
    ('express-js', 'Express.js', 'Software', 'expressjs'),
    ('rest-apis', 'REST APIs', 'Software', 'restapis'),
    ('graphql', 'GraphQL', 'Software', 'graphql'),
    ('html', 'HTML', 'Software', 'html'),
    ('css', 'CSS', 'Software', 'css'),
    ('tailwind-css', 'Tailwind CSS', 'Software', 'tailwindcss'),
    ('sass', 'Sass', 'Software', 'sass'),
    ('git', 'Git', 'Software', 'git'),
    ('github', 'GitHub', 'Software', 'github'),
    ('ci-cd', 'CI/CD', 'Software', 'cicd'),
    ('unit-testing', 'Unit Testing', 'Software', 'unittesting'),
    ('integration-testing', 'Integration Testing', 'Software', 'integrationtesting'),
    ('jest', 'Jest', 'Software', 'jest'),
    ('playwright', 'Playwright', 'Software', 'playwright'),
    ('docker', 'Docker', 'Software', 'docker'),
    ('kubernetes-basics', 'Kubernetes Basics', 'Software', 'kubernetesbasics'),
    ('linux', 'Linux', 'Software', 'linux'),
    ('bash', 'Bash', 'Software', 'bash'),
    ('json', 'JSON', 'Software', 'json'),
    ('oauth', 'OAuth', 'Software', 'oauth'),
    ('authentication', 'Authentication', 'Software', 'authentication'),
    ('authorization', 'Authorization', 'Software', 'authorization'),
    ('api-integration', 'API Integration', 'Software', 'apiintegration'),
    ('system-design', 'System Design', 'Software', 'systemdesign'),
    ('agile-development', 'Agile Development', 'Software', 'agiledevelopment'),
    ('aws-basics', 'AWS Basics', 'Cloud', 'awsbasics'),
    ('amazon-s3', 'Amazon S3', 'Cloud', 'amazons3'),
    ('aws-lambda', 'AWS Lambda', 'Cloud', 'awslambda'),
    ('cloudwatch', 'CloudWatch', 'Cloud', 'cloudwatch'),
    ('google-cloud-basics', 'Google Cloud Basics', 'Cloud', 'googlecloudbasics'),
    ('azure-basics', 'Azure Basics', 'Cloud', 'azurebasics'),
    ('vercel-deployment', 'Vercel Deployment', 'Cloud', 'verceldeployment'),
    ('netlify-deployment', 'Netlify Deployment', 'Cloud', 'netlifydeployment'),
    ('infrastructure-as-code', 'Infrastructure as Code', 'Cloud', 'infrastructureascode'),
    ('terraform-basics', 'Terraform Basics', 'Cloud', 'terraformbasics'),
    ('serverless-basics', 'Serverless Basics', 'Cloud', 'serverlessbasics'),
    ('cdn-fundamentals', 'CDN Fundamentals', 'Cloud', 'cdnfundamentals'),
    ('cloud-security-basics', 'Cloud Security Basics', 'Cloud', 'cloudsecuritybasics'),
    ('monitoring-and-alerting', 'Monitoring and Alerting', 'Cloud', 'monitoringandalerting'),
    ('incident-response', 'Incident Response', 'Cloud', 'incidentresponse'),
    ('seo', 'SEO', 'Marketing', 'seo'),
    ('sem', 'SEM', 'Marketing', 'sem'),
    ('google-ads', 'Google Ads', 'Marketing', 'googleads'),
    ('meta-ads', 'Meta Ads', 'Marketing', 'metaads'),
    ('linkedin-ads', 'LinkedIn Ads', 'Marketing', 'linkedinads'),
    ('email-marketing', 'Email Marketing', 'Marketing', 'emailmarketing'),
    ('lifecycle-marketing', 'Lifecycle Marketing', 'Marketing', 'lifecyclemarketing'),
    ('marketing-automation', 'Marketing Automation', 'Marketing', 'marketingautomation'),
    ('hubspot', 'HubSpot', 'Marketing', 'hubspot'),
    ('salesforce-crm', 'Salesforce CRM', 'Marketing', 'salesforcecrm'),
    ('content-marketing', 'Content Marketing', 'Marketing', 'contentmarketing'),
    ('copywriting', 'Copywriting', 'Marketing', 'copywriting'),
    ('social-media-management', 'Social Media Management', 'Marketing', 'socialmediamanagement'),
    ('influencer-marketing', 'Influencer Marketing', 'Marketing', 'influencermarketing'),
    ('brand-strategy', 'Brand Strategy', 'Marketing', 'brandstrategy'),
    ('campaign-planning', 'Campaign Planning', 'Marketing', 'campaignplanning'),
    ('market-research', 'Market Research', 'Marketing', 'marketresearch'),
    ('competitive-analysis', 'Competitive Analysis', 'Marketing', 'competitiveanalysis'),
    ('conversion-rate-optimization', 'Conversion Rate Optimization', 'Marketing', 'conversionrateoptimization'),
    ('web-analytics', 'Web Analytics', 'Marketing', 'webanalytics'),
    ('google-analytics', 'Google Analytics', 'Marketing', 'googleanalytics'),
    ('a-b-creative-testing', 'A/B Creative Testing', 'Marketing', 'abcreativetesting'),
    ('landing-page-optimization', 'Landing Page Optimization', 'Marketing', 'landingpageoptimization'),
    ('pr-outreach', 'PR Outreach', 'Marketing', 'proutreach'),
    ('event-marketing', 'Event Marketing', 'Marketing', 'eventmarketing'),
    ('project-management', 'Project Management', 'Operations', 'projectmanagement'),
    ('program-management', 'Program Management', 'Operations', 'programmanagement'),
    ('operations-analysis', 'Operations Analysis', 'Operations', 'operationsanalysis'),
    ('process-improvement', 'Process Improvement', 'Operations', 'processimprovement'),
    ('lean', 'Lean', 'Operations', 'lean'),
    ('six-sigma', 'Six Sigma', 'Operations', 'sixsigma'),
    ('kaizen', 'Kaizen', 'Operations', 'kaizen'),
    ('sop-development', 'SOP Development', 'Operations', 'sopdevelopment'),
    ('capacity-planning', 'Capacity Planning', 'Operations', 'capacityplanning'),
    ('supply-chain-fundamentals', 'Supply Chain Fundamentals', 'Operations', 'supplychainfundamentals'),
    ('procurement', 'Procurement', 'Operations', 'procurement'),
    ('inventory-management', 'Inventory Management', 'Operations', 'inventorymanagement'),
    ('logistics-coordination', 'Logistics Coordination', 'Operations', 'logisticscoordination'),
    ('quality-assurance', 'Quality Assurance', 'Operations', 'qualityassurance'),
    ('kpi-tracking', 'KPI Tracking', 'Operations', 'kpitracking'),
    ('okr-planning', 'OKR Planning', 'Operations', 'okrplanning'),
    ('resource-planning', 'Resource Planning', 'Operations', 'resourceplanning'),
    ('scheduling', 'Scheduling', 'Operations', 'scheduling'),
    ('workforce-planning', 'Workforce Planning', 'Operations', 'workforceplanning'),
    ('risk-register-management', 'Risk Register Management', 'Operations', 'riskregistermanagement'),
    ('compliance-operations', 'Compliance Operations', 'Operations', 'complianceoperations'),
    ('documentation-control', 'Documentation Control', 'Operations', 'documentationcontrol'),
    ('prospecting', 'Prospecting', 'Sales', 'prospecting'),
    ('lead-qualification', 'Lead Qualification', 'Sales', 'leadqualification'),
    ('pipeline-management', 'Pipeline Management', 'Sales', 'pipelinemanagement'),
    ('crm-hygiene', 'CRM Hygiene', 'Sales', 'crmhygiene'),
    ('discovery-calls', 'Discovery Calls', 'Sales', 'discoverycalls'),
    ('objection-handling', 'Objection Handling', 'Sales', 'objectionhandling'),
    ('negotiation-for-sales', 'Negotiation for Sales', 'Sales', 'negotiationforsales'),
    ('account-management', 'Account Management', 'Sales', 'accountmanagement'),
    ('customer-success', 'Customer Success', 'Sales', 'customersuccess'),
    ('upselling', 'Upselling', 'Sales', 'upselling'),
    ('cross-selling', 'Cross-selling', 'Sales', 'crossselling'),
    ('sales-forecasting', 'Sales Forecasting', 'Sales', 'salesforecasting'),
    ('territory-planning', 'Territory Planning', 'Sales', 'territoryplanning'),
    ('cold-email', 'Cold Email', 'Sales', 'coldemail'),
    ('cold-calling', 'Cold Calling', 'Sales', 'coldcalling'),
    ('demo-delivery', 'Demo Delivery', 'Sales', 'demodelivery'),
    ('contract-review-support', 'Contract Review Support', 'Sales', 'contractreviewsupport'),
    ('renewal-management', 'Renewal Management', 'Sales', 'renewalmanagement'),
    ('figma', 'Figma', 'Design', 'figma'),
    ('wireframing', 'Wireframing', 'Design', 'wireframing'),
    ('prototyping', 'Prototyping', 'Design', 'prototyping'),
    ('user-research', 'User Research', 'Design', 'userresearch'),
    ('usability-testing', 'Usability Testing', 'Design', 'usabilitytesting'),
    ('interaction-design', 'Interaction Design', 'Design', 'interactiondesign'),
    ('information-architecture', 'Information Architecture', 'Design', 'informationarchitecture'),
    ('visual-design', 'Visual Design', 'Design', 'visualdesign'),
    ('design-systems', 'Design Systems', 'Design', 'designsystems'),
    ('accessibility-wcag', 'Accessibility (WCAG)', 'Design', 'accessibilitywcag'),
    ('adobe-photoshop', 'Adobe Photoshop', 'Design', 'adobephotoshop'),
    ('adobe-illustrator', 'Adobe Illustrator', 'Design', 'adobeillustrator'),
    ('canva', 'Canva', 'Design', 'canva'),
    ('typography', 'Typography', 'Design', 'typography'),
    ('brand-identity', 'Brand Identity', 'Design', 'brandidentity'),
    ('motion-design-basics', 'Motion Design Basics', 'Design', 'motiondesignbasics'),
    ('journey-mapping', 'Journey Mapping', 'Design', 'journeymapping'),
    ('persona-development', 'Persona Development', 'Design', 'personadevelopment'),
    ('healthcare-administration', 'Healthcare Administration', 'Healthcare', 'healthcareadministration'),
    ('medical-billing', 'Medical Billing', 'Healthcare', 'medicalbilling'),
    ('medical-coding-basics', 'Medical Coding Basics', 'Healthcare', 'medicalcodingbasics'),
    ('hipaa-compliance', 'HIPAA Compliance', 'Healthcare', 'hipaacompliance'),
    ('electronic-health-records', 'Electronic Health Records', 'Healthcare', 'electronichealthrecords'),
    ('patient-scheduling', 'Patient Scheduling', 'Healthcare', 'patientscheduling'),
    ('revenue-cycle-management', 'Revenue Cycle Management', 'Healthcare', 'revenuecyclemanagement'),
    ('clinical-documentation', 'Clinical Documentation', 'Healthcare', 'clinicaldocumentation'),
    ('insurance-verification', 'Insurance Verification', 'Healthcare', 'insuranceverification'),
    ('healthcare-data-entry', 'Healthcare Data Entry', 'Healthcare', 'healthcaredataentry'),
    ('care-coordination', 'Care Coordination', 'Healthcare', 'carecoordination'),
    ('prior-authorization', 'Prior Authorization', 'Healthcare', 'priorauthorization'),
    ('construction-management', 'Construction Management', 'Construction', 'constructionmanagement'),
    ('blueprint-reading', 'Blueprint Reading', 'Construction', 'blueprintreading'),
    ('cost-estimation', 'Cost Estimation', 'Construction', 'costestimation'),
    ('bid-coordination', 'Bid Coordination', 'Construction', 'bidcoordination'),
    ('subcontractor-coordination', 'Subcontractor Coordination', 'Construction', 'subcontractorcoordination'),
    ('site-safety-basics', 'Site Safety Basics', 'Construction', 'sitesafetybasics'),
    ('osha-basics', 'OSHA Basics', 'Construction', 'oshabasics'),
    ('scheduling-construction', 'Scheduling (Construction)', 'Construction', 'schedulingconstruction'),
    ('rfi-management', 'RFI Management', 'Construction', 'rfimanagement'),
    ('change-order-management', 'Change Order Management', 'Construction', 'changeordermanagement'),
    ('construction-procurement', 'Construction Procurement', 'Construction', 'constructionprocurement'),
    ('field-reporting', 'Field Reporting', 'Construction', 'fieldreporting'),
    ('hospitality-operations', 'Hospitality Operations', 'Hospitality', 'hospitalityoperations'),
    ('front-desk-operations', 'Front Desk Operations', 'Hospitality', 'frontdeskoperations'),
    ('guest-services', 'Guest Services', 'Hospitality', 'guestservices'),
    ('reservation-management', 'Reservation Management', 'Hospitality', 'reservationmanagement'),
    ('event-coordination', 'Event Coordination', 'Hospitality', 'eventcoordination'),
    ('food-and-beverage-operations', 'Food and Beverage Operations', 'Hospitality', 'foodandbeverageoperations'),
    ('housekeeping-coordination', 'Housekeeping Coordination', 'Hospitality', 'housekeepingcoordination'),
    ('revenue-management-hospitality', 'Revenue Management (Hospitality)', 'Hospitality', 'revenuemanagementhospitality'),
    ('pos-systems', 'POS Systems', 'Hospitality', 'possystems'),
    ('customer-recovery', 'Customer Recovery', 'Hospitality', 'customerrecovery'),
    ('communication', 'Communication', 'Professional', 'communication'),
    ('teamwork', 'Teamwork', 'Professional', 'teamwork'),
    ('leadership', 'Leadership', 'Professional', 'leadership'),
    ('customer-service', 'Customer Service', 'Professional', 'customerservice'),
    ('adaptability', 'Adaptability', 'Professional', 'adaptability'),
    ('critical-thinking', 'Critical Thinking', 'Professional', 'criticalthinking'),
    ('attention-to-detail', 'Attention to Detail', 'Professional', 'attentiontodetail'),
    ('organization', 'Organization', 'Professional', 'organization'),
    ('accountability', 'Accountability', 'Professional', 'accountability'),
    ('initiative', 'Initiative', 'Professional', 'initiative'),
    ('conflict-resolution', 'Conflict Resolution', 'Professional', 'conflictresolution'),
    ('coaching', 'Coaching', 'Professional', 'coaching'),
    ('mentoring', 'Mentoring', 'Professional', 'mentoring'),
    ('emotional-intelligence', 'Emotional Intelligence', 'Professional', 'emotionalintelligence'),
    ('multitasking', 'Multitasking', 'Professional', 'multitasking'),
    ('professional-writing', 'Professional Writing', 'Professional', 'professionalwriting'),
    ('presentation-delivery', 'Presentation Delivery', 'Professional', 'presentationdelivery'),
    ('collaboration', 'Collaboration', 'Professional', 'collaboration'),
    ('analytical-thinking', 'Analytical Thinking', 'Professional', 'analyticalthinking'),
    ('reliability', 'Reliability', 'Professional', 'reliability')
), mapped as (
  select
    i.slug,
    i.label,
    i.category_name,
    i.normalized_name,
    c.id as category_id
  from incoming i
  left join public.canonical_skill_categories c on c.slug = lower(regexp_replace(i.category_name, '[^a-z0-9]+', '-', 'g'))
)
insert into public.skills (slug, label, category, category_id, normalized_name, is_active)
select slug, label, category_name, category_id, normalized_name, true
from mapped
on conflict (slug) do update
set
  label = excluded.label,
  category = excluded.category,
  category_id = excluded.category_id,
  normalized_name = coalesce(public.skills.normalized_name, excluded.normalized_name),
  is_active = true,
  updated_at = now();

with alias_map(alias, slug) as (
  values
    ('microsoft-excel', 'microsoft-excel'),
    ('microsoftexcel', 'microsoft-excel'),
    ('microsoft excel', 'microsoft-excel'),
    ('excel', 'microsoft-excel'),
    ('ms excel', 'microsoft-excel'),
    ('excel advanced', 'microsoft-excel'),
    ('excel pivot tables', 'excel-pivot-tables'),
    ('microsoft-powerpoint', 'microsoft-powerpoint'),
    ('microsoftpowerpoint', 'microsoft-powerpoint'),
    ('microsoft powerpoint', 'microsoft-powerpoint'),
    ('powerpoint', 'microsoft-powerpoint'),
    ('ms powerpoint', 'microsoft-powerpoint'),
    ('microsoft-word', 'microsoft-word'),
    ('microsoftword', 'microsoft-word'),
    ('microsoft word', 'microsoft-word'),
    ('business-writing', 'business-writing'),
    ('businesswriting', 'business-writing'),
    ('business writing', 'business-writing'),
    ('business-communication', 'business-communication'),
    ('businesscommunication', 'business-communication'),
    ('business communication', 'business-communication'),
    ('stakeholder-management', 'stakeholder-management'),
    ('stakeholdermanagement', 'stakeholder-management'),
    ('stakeholder management', 'stakeholder-management'),
    ('project-coordination', 'project-coordination'),
    ('projectcoordination', 'project-coordination'),
    ('project coordination', 'project-coordination'),
    ('strategic-planning', 'strategic-planning'),
    ('strategicplanning', 'strategic-planning'),
    ('strategic planning', 'strategic-planning'),
    ('business-analysis', 'business-analysis'),
    ('businessanalysis', 'business-analysis'),
    ('business analysis', 'business-analysis'),
    ('requirements-gathering', 'requirements-gathering'),
    ('requirementsgathering', 'requirements-gathering'),
    ('requirements gathering', 'requirements-gathering'),
    ('process-documentation', 'process-documentation'),
    ('processdocumentation', 'process-documentation'),
    ('process documentation', 'process-documentation'),
    ('change-management', 'change-management'),
    ('changemanagement', 'change-management'),
    ('change management', 'change-management'),
    ('client-relations', 'client-relations'),
    ('clientrelations', 'client-relations'),
    ('client relations', 'client-relations'),
    ('vendor-management', 'vendor-management'),
    ('vendormanagement', 'vendor-management'),
    ('vendor management', 'vendor-management'),
    ('negotiation', 'negotiation'),
    ('meeting-facilitation', 'meeting-facilitation'),
    ('meetingfacilitation', 'meeting-facilitation'),
    ('meeting facilitation', 'meeting-facilitation'),
    ('presentation-skills', 'presentation-skills'),
    ('presentationskills', 'presentation-skills'),
    ('presentation skills', 'presentation-skills'),
    ('public-speaking', 'public-speaking'),
    ('publicspeaking', 'public-speaking'),
    ('public speaking', 'public-speaking'),
    ('time-management', 'time-management'),
    ('timemanagement', 'time-management'),
    ('time management', 'time-management'),
    ('cross-functional-collaboration', 'cross-functional-collaboration'),
    ('crossfunctionalcollaboration', 'cross-functional-collaboration'),
    ('cross-functional collaboration', 'cross-functional-collaboration'),
    ('decision-making', 'decision-making'),
    ('decisionmaking', 'decision-making'),
    ('decision making', 'decision-making'),
    ('problem-solving', 'problem-solving'),
    ('problemsolving', 'problem-solving'),
    ('problem solving', 'problem-solving'),
    ('professional-etiquette', 'professional-etiquette'),
    ('professionaletiquette', 'professional-etiquette'),
    ('professional etiquette', 'professional-etiquette'),
    ('financial-modeling', 'financial-modeling'),
    ('financialmodeling', 'financial-modeling'),
    ('financial modeling', 'financial-modeling'),
    ('valuation', 'valuation'),
    ('financial-statement-analysis', 'financial-statement-analysis'),
    ('financialstatementanalysis', 'financial-statement-analysis'),
    ('financial statement analysis', 'financial-statement-analysis'),
    ('gaap', 'gaap'),
    ('budgeting', 'budgeting'),
    ('forecasting', 'forecasting'),
    ('variance-analysis', 'variance-analysis'),
    ('varianceanalysis', 'variance-analysis'),
    ('variance analysis', 'variance-analysis'),
    ('cash-flow-analysis', 'cash-flow-analysis'),
    ('cashflowanalysis', 'cash-flow-analysis'),
    ('cash flow analysis', 'cash-flow-analysis'),
    ('corporate-finance', 'corporate-finance'),
    ('corporatefinance', 'corporate-finance'),
    ('corporate finance', 'corporate-finance'),
    ('investment-analysis', 'investment-analysis'),
    ('investmentanalysis', 'investment-analysis'),
    ('investment analysis', 'investment-analysis'),
    ('equity-research', 'equity-research'),
    ('equityresearch', 'equity-research'),
    ('equity research', 'equity-research'),
    ('credit-analysis', 'credit-analysis'),
    ('creditanalysis', 'credit-analysis'),
    ('credit analysis', 'credit-analysis'),
    ('mergers-and-acquisitions', 'mergers-and-acquisitions'),
    ('mergersandacquisitions', 'mergers-and-acquisitions'),
    ('mergers and acquisitions', 'mergers-and-acquisitions'),
    ('due-diligence', 'due-diligence'),
    ('duediligence', 'due-diligence'),
    ('due diligence', 'due-diligence'),
    ('capital-markets', 'capital-markets'),
    ('capitalmarkets', 'capital-markets'),
    ('capital markets', 'capital-markets'),
    ('portfolio-analysis', 'portfolio-analysis'),
    ('portfolioanalysis', 'portfolio-analysis'),
    ('portfolio analysis', 'portfolio-analysis'),
    ('risk-management', 'risk-management'),
    ('riskmanagement', 'risk-management'),
    ('risk management', 'risk-management'),
    ('treasury-operations', 'treasury-operations'),
    ('treasuryoperations', 'treasury-operations'),
    ('treasury operations', 'treasury-operations'),
    ('quickbooks', 'quickbooks'),
    ('accounts-payable', 'accounts-payable'),
    ('accountspayable', 'accounts-payable'),
    ('accounts payable', 'accounts-payable'),
    ('accounts-receivable', 'accounts-receivable'),
    ('accountsreceivable', 'accounts-receivable'),
    ('accounts receivable', 'accounts-receivable'),
    ('reconciliations', 'reconciliations'),
    ('audit-support', 'audit-support'),
    ('auditsupport', 'audit-support'),
    ('audit support', 'audit-support'),
    ('tax-preparation', 'tax-preparation'),
    ('taxpreparation', 'tax-preparation'),
    ('tax preparation', 'tax-preparation'),
    ('payroll-processing', 'payroll-processing'),
    ('payrollprocessing', 'payroll-processing'),
    ('payroll processing', 'payroll-processing'),
    ('internal-controls', 'internal-controls'),
    ('internalcontrols', 'internal-controls'),
    ('internal controls', 'internal-controls'),
    ('cost-accounting', 'cost-accounting'),
    ('costaccounting', 'cost-accounting'),
    ('cost accounting', 'cost-accounting'),
    ('managerial-accounting', 'managerial-accounting'),
    ('managerialaccounting', 'managerial-accounting'),
    ('managerial accounting', 'managerial-accounting'),
    ('fund-accounting', 'fund-accounting'),
    ('fundaccounting', 'fund-accounting'),
    ('fund accounting', 'fund-accounting'),
    ('revenue-recognition', 'revenue-recognition'),
    ('revenuerecognition', 'revenue-recognition'),
    ('revenue recognition', 'revenue-recognition'),
    ('sql', 'sql'),
    ('postgresql', 'postgresql'),
    ('mysql', 'mysql'),
    ('sqlite', 'sqlite'),
    ('data-cleaning', 'data-cleaning'),
    ('datacleaning', 'data-cleaning'),
    ('data cleaning', 'data-cleaning'),
    ('data-wrangling', 'data-wrangling'),
    ('datawrangling', 'data-wrangling'),
    ('data wrangling', 'data-wrangling'),
    ('exploratory-data-analysis', 'exploratory-data-analysis'),
    ('exploratorydataanalysis', 'exploratory-data-analysis'),
    ('exploratory data analysis', 'exploratory-data-analysis'),
    ('statistical-analysis', 'statistical-analysis'),
    ('statisticalanalysis', 'statistical-analysis'),
    ('statistical analysis', 'statistical-analysis'),
    ('a-b-testing', 'a-b-testing'),
    ('abtesting', 'a-b-testing'),
    ('a/b testing', 'a-b-testing'),
    ('ab testing', 'a-b-testing'),
    ('a b testing', 'a-b-testing'),
    ('hypothesis-testing', 'hypothesis-testing'),
    ('hypothesistesting', 'hypothesis-testing'),
    ('hypothesis testing', 'hypothesis-testing'),
    ('regression-analysis', 'regression-analysis'),
    ('regressionanalysis', 'regression-analysis'),
    ('regression analysis', 'regression-analysis'),
    ('data-visualization', 'data-visualization'),
    ('datavisualization', 'data-visualization'),
    ('data visualization', 'data-visualization'),
    ('dashboarding', 'dashboarding'),
    ('tableau', 'tableau'),
    ('power-bi', 'power-bi'),
    ('powerbi', 'power-bi'),
    ('power bi', 'power-bi'),
    ('looker-studio', 'looker-studio'),
    ('lookerstudio', 'looker-studio'),
    ('looker studio', 'looker-studio'),
    ('excel-pivot-tables', 'excel-pivot-tables'),
    ('excelpivottables', 'excel-pivot-tables'),
    ('excel-xlookup', 'excel-xlookup'),
    ('excelxlookup', 'excel-xlookup'),
    ('excel xlookup', 'excel-xlookup'),
    ('xlookup', 'excel-xlookup'),
    ('excel-vlookup', 'excel-vlookup'),
    ('excelvlookup', 'excel-vlookup'),
    ('excel vlookup', 'excel-vlookup'),
    ('vlookup', 'excel-vlookup'),
    ('google-sheets', 'google-sheets'),
    ('googlesheets', 'google-sheets'),
    ('google sheets', 'google-sheets'),
    ('g sheets', 'google-sheets'),
    ('python-for-analytics', 'python-for-analytics'),
    ('pythonforanalytics', 'python-for-analytics'),
    ('python for analytics', 'python-for-analytics'),
    ('r-programming', 'r-programming'),
    ('rprogramming', 'r-programming'),
    ('r programming', 'r-programming'),
    ('jupyter', 'jupyter'),
    ('pandas', 'pandas'),
    ('numpy', 'numpy'),
    ('etl', 'etl'),
    ('data-modeling', 'data-modeling'),
    ('datamodeling', 'data-modeling'),
    ('data modeling', 'data-modeling'),
    ('data-governance', 'data-governance'),
    ('datagovernance', 'data-governance'),
    ('data governance', 'data-governance'),
    ('data-quality', 'data-quality'),
    ('dataquality', 'data-quality'),
    ('data quality', 'data-quality'),
    ('business-intelligence', 'business-intelligence'),
    ('businessintelligence', 'business-intelligence'),
    ('business intelligence', 'business-intelligence'),
    ('javascript', 'javascript'),
    ('js', 'javascript'),
    ('typescript', 'typescript'),
    ('ts', 'typescript'),
    ('react', 'react'),
    ('next-js', 'next-js'),
    ('nextjs', 'next-js'),
    ('next.js', 'next-js'),
    ('next js', 'next-js'),
    ('node-js', 'node-js'),
    ('nodejs', 'node-js'),
    ('node.js', 'node-js'),
    ('node js', 'node-js'),
    ('express-js', 'express-js'),
    ('expressjs', 'express-js'),
    ('express.js', 'express-js'),
    ('rest-apis', 'rest-apis'),
    ('restapis', 'rest-apis'),
    ('rest apis', 'rest-apis'),
    ('rest api', 'rest-apis'),
    ('restful api', 'rest-apis'),
    ('apis', 'rest-apis'),
    ('graphql', 'graphql'),
    ('html', 'html'),
    ('css', 'css'),
    ('tailwind-css', 'tailwind-css'),
    ('tailwindcss', 'tailwind-css'),
    ('tailwind css', 'tailwind-css'),
    ('sass', 'sass'),
    ('git', 'git'),
    ('github', 'github'),
    ('ci-cd', 'ci-cd'),
    ('cicd', 'ci-cd'),
    ('ci/cd', 'ci-cd'),
    ('continuous integration', 'ci-cd'),
    ('continuous delivery', 'ci-cd'),
    ('unit-testing', 'unit-testing'),
    ('unittesting', 'unit-testing'),
    ('unit testing', 'unit-testing'),
    ('integration-testing', 'integration-testing'),
    ('integrationtesting', 'integration-testing'),
    ('integration testing', 'integration-testing'),
    ('jest', 'jest'),
    ('playwright', 'playwright'),
    ('docker', 'docker'),
    ('kubernetes-basics', 'kubernetes-basics'),
    ('kubernetesbasics', 'kubernetes-basics'),
    ('kubernetes basics', 'kubernetes-basics'),
    ('linux', 'linux'),
    ('bash', 'bash'),
    ('json', 'json'),
    ('oauth', 'oauth'),
    ('authentication', 'authentication'),
    ('authorization', 'authorization'),
    ('api-integration', 'api-integration'),
    ('apiintegration', 'api-integration'),
    ('api integration', 'api-integration'),
    ('system-design', 'system-design'),
    ('systemdesign', 'system-design'),
    ('system design', 'system-design'),
    ('agile-development', 'agile-development'),
    ('agiledevelopment', 'agile-development'),
    ('agile development', 'agile-development'),
    ('aws-basics', 'aws-basics'),
    ('awsbasics', 'aws-basics'),
    ('aws basics', 'aws-basics'),
    ('amazon-s3', 'amazon-s3'),
    ('amazons3', 'amazon-s3'),
    ('amazon s3', 'amazon-s3'),
    ('aws-lambda', 'aws-lambda'),
    ('awslambda', 'aws-lambda'),
    ('aws lambda', 'aws-lambda'),
    ('cloudwatch', 'cloudwatch'),
    ('google-cloud-basics', 'google-cloud-basics'),
    ('googlecloudbasics', 'google-cloud-basics'),
    ('google cloud basics', 'google-cloud-basics'),
    ('azure-basics', 'azure-basics'),
    ('azurebasics', 'azure-basics'),
    ('azure basics', 'azure-basics'),
    ('vercel-deployment', 'vercel-deployment'),
    ('verceldeployment', 'vercel-deployment'),
    ('vercel deployment', 'vercel-deployment'),
    ('netlify-deployment', 'netlify-deployment'),
    ('netlifydeployment', 'netlify-deployment'),
    ('netlify deployment', 'netlify-deployment'),
    ('infrastructure-as-code', 'infrastructure-as-code'),
    ('infrastructureascode', 'infrastructure-as-code'),
    ('infrastructure as code', 'infrastructure-as-code'),
    ('terraform-basics', 'terraform-basics'),
    ('terraformbasics', 'terraform-basics'),
    ('terraform basics', 'terraform-basics'),
    ('serverless-basics', 'serverless-basics'),
    ('serverlessbasics', 'serverless-basics'),
    ('serverless basics', 'serverless-basics'),
    ('cdn-fundamentals', 'cdn-fundamentals'),
    ('cdnfundamentals', 'cdn-fundamentals'),
    ('cdn fundamentals', 'cdn-fundamentals'),
    ('cloud-security-basics', 'cloud-security-basics'),
    ('cloudsecuritybasics', 'cloud-security-basics'),
    ('cloud security basics', 'cloud-security-basics'),
    ('monitoring-and-alerting', 'monitoring-and-alerting'),
    ('monitoringandalerting', 'monitoring-and-alerting'),
    ('monitoring and alerting', 'monitoring-and-alerting'),
    ('incident-response', 'incident-response'),
    ('incidentresponse', 'incident-response'),
    ('incident response', 'incident-response'),
    ('seo', 'seo'),
    ('sem', 'sem'),
    ('google-ads', 'google-ads'),
    ('googleads', 'google-ads'),
    ('google ads', 'google-ads'),
    ('meta-ads', 'meta-ads'),
    ('metaads', 'meta-ads'),
    ('meta ads', 'meta-ads'),
    ('linkedin-ads', 'linkedin-ads'),
    ('linkedinads', 'linkedin-ads'),
    ('linkedin ads', 'linkedin-ads'),
    ('email-marketing', 'email-marketing'),
    ('emailmarketing', 'email-marketing'),
    ('email marketing', 'email-marketing'),
    ('lifecycle-marketing', 'lifecycle-marketing'),
    ('lifecyclemarketing', 'lifecycle-marketing'),
    ('lifecycle marketing', 'lifecycle-marketing'),
    ('marketing-automation', 'marketing-automation'),
    ('marketingautomation', 'marketing-automation'),
    ('marketing automation', 'marketing-automation'),
    ('hubspot', 'hubspot'),
    ('salesforce-crm', 'salesforce-crm'),
    ('salesforcecrm', 'salesforce-crm'),
    ('salesforce crm', 'salesforce-crm'),
    ('salesforce', 'salesforce-crm'),
    ('content-marketing', 'content-marketing'),
    ('contentmarketing', 'content-marketing'),
    ('content marketing', 'content-marketing'),
    ('copywriting', 'copywriting'),
    ('social-media-management', 'social-media-management'),
    ('socialmediamanagement', 'social-media-management'),
    ('social media management', 'social-media-management'),
    ('influencer-marketing', 'influencer-marketing'),
    ('influencermarketing', 'influencer-marketing'),
    ('influencer marketing', 'influencer-marketing'),
    ('brand-strategy', 'brand-strategy'),
    ('brandstrategy', 'brand-strategy'),
    ('brand strategy', 'brand-strategy'),
    ('campaign-planning', 'campaign-planning'),
    ('campaignplanning', 'campaign-planning'),
    ('campaign planning', 'campaign-planning'),
    ('market-research', 'market-research'),
    ('marketresearch', 'market-research'),
    ('market research', 'market-research'),
    ('competitive-analysis', 'competitive-analysis'),
    ('competitiveanalysis', 'competitive-analysis'),
    ('competitive analysis', 'competitive-analysis'),
    ('conversion-rate-optimization', 'conversion-rate-optimization'),
    ('conversionrateoptimization', 'conversion-rate-optimization'),
    ('conversion rate optimization', 'conversion-rate-optimization'),
    ('web-analytics', 'web-analytics'),
    ('webanalytics', 'web-analytics'),
    ('web analytics', 'web-analytics'),
    ('google-analytics', 'google-analytics'),
    ('googleanalytics', 'google-analytics'),
    ('google analytics', 'google-analytics'),
    ('a-b-creative-testing', 'a-b-creative-testing'),
    ('abcreativetesting', 'a-b-creative-testing'),
    ('a/b creative testing', 'a-b-creative-testing'),
    ('creative ab testing', 'a-b-creative-testing'),
    ('landing-page-optimization', 'landing-page-optimization'),
    ('landingpageoptimization', 'landing-page-optimization'),
    ('landing page optimization', 'landing-page-optimization'),
    ('pr-outreach', 'pr-outreach'),
    ('proutreach', 'pr-outreach'),
    ('pr outreach', 'pr-outreach'),
    ('event-marketing', 'event-marketing'),
    ('eventmarketing', 'event-marketing'),
    ('event marketing', 'event-marketing'),
    ('project-management', 'project-management'),
    ('projectmanagement', 'project-management'),
    ('project management', 'project-management'),
    ('program-management', 'program-management'),
    ('programmanagement', 'program-management'),
    ('program management', 'program-management'),
    ('operations-analysis', 'operations-analysis'),
    ('operationsanalysis', 'operations-analysis'),
    ('operations analysis', 'operations-analysis'),
    ('process-improvement', 'process-improvement'),
    ('processimprovement', 'process-improvement'),
    ('process improvement', 'process-improvement'),
    ('lean', 'lean'),
    ('six-sigma', 'six-sigma'),
    ('sixsigma', 'six-sigma'),
    ('six sigma', 'six-sigma'),
    ('kaizen', 'kaizen'),
    ('sop-development', 'sop-development'),
    ('sopdevelopment', 'sop-development'),
    ('sop development', 'sop-development'),
    ('capacity-planning', 'capacity-planning'),
    ('capacityplanning', 'capacity-planning'),
    ('capacity planning', 'capacity-planning'),
    ('supply-chain-fundamentals', 'supply-chain-fundamentals'),
    ('supplychainfundamentals', 'supply-chain-fundamentals'),
    ('supply chain fundamentals', 'supply-chain-fundamentals'),
    ('procurement', 'procurement'),
    ('inventory-management', 'inventory-management'),
    ('inventorymanagement', 'inventory-management'),
    ('inventory management', 'inventory-management'),
    ('logistics-coordination', 'logistics-coordination'),
    ('logisticscoordination', 'logistics-coordination'),
    ('logistics coordination', 'logistics-coordination'),
    ('quality-assurance', 'quality-assurance'),
    ('qualityassurance', 'quality-assurance'),
    ('quality assurance', 'quality-assurance'),
    ('kpi-tracking', 'kpi-tracking'),
    ('kpitracking', 'kpi-tracking'),
    ('kpi tracking', 'kpi-tracking'),
    ('okr-planning', 'okr-planning'),
    ('okrplanning', 'okr-planning'),
    ('okr planning', 'okr-planning'),
    ('resource-planning', 'resource-planning'),
    ('resourceplanning', 'resource-planning'),
    ('resource planning', 'resource-planning'),
    ('scheduling', 'scheduling'),
    ('workforce-planning', 'workforce-planning'),
    ('workforceplanning', 'workforce-planning'),
    ('workforce planning', 'workforce-planning'),
    ('risk-register-management', 'risk-register-management'),
    ('riskregistermanagement', 'risk-register-management'),
    ('risk register management', 'risk-register-management'),
    ('compliance-operations', 'compliance-operations'),
    ('complianceoperations', 'compliance-operations'),
    ('compliance operations', 'compliance-operations'),
    ('documentation-control', 'documentation-control'),
    ('documentationcontrol', 'documentation-control'),
    ('documentation control', 'documentation-control'),
    ('prospecting', 'prospecting'),
    ('lead-qualification', 'lead-qualification'),
    ('leadqualification', 'lead-qualification'),
    ('lead qualification', 'lead-qualification'),
    ('pipeline-management', 'pipeline-management'),
    ('pipelinemanagement', 'pipeline-management'),
    ('pipeline management', 'pipeline-management'),
    ('crm-hygiene', 'crm-hygiene'),
    ('crmhygiene', 'crm-hygiene'),
    ('crm hygiene', 'crm-hygiene'),
    ('discovery-calls', 'discovery-calls'),
    ('discoverycalls', 'discovery-calls'),
    ('discovery calls', 'discovery-calls'),
    ('objection-handling', 'objection-handling'),
    ('objectionhandling', 'objection-handling'),
    ('objection handling', 'objection-handling'),
    ('negotiation-for-sales', 'negotiation-for-sales'),
    ('negotiationforsales', 'negotiation-for-sales'),
    ('negotiation for sales', 'negotiation-for-sales'),
    ('account-management', 'account-management'),
    ('accountmanagement', 'account-management'),
    ('account management', 'account-management'),
    ('customer-success', 'customer-success'),
    ('customersuccess', 'customer-success'),
    ('customer success', 'customer-success'),
    ('upselling', 'upselling'),
    ('cross-selling', 'cross-selling'),
    ('crossselling', 'cross-selling'),
    ('sales-forecasting', 'sales-forecasting'),
    ('salesforecasting', 'sales-forecasting'),
    ('sales forecasting', 'sales-forecasting'),
    ('territory-planning', 'territory-planning'),
    ('territoryplanning', 'territory-planning'),
    ('territory planning', 'territory-planning'),
    ('cold-email', 'cold-email'),
    ('coldemail', 'cold-email'),
    ('cold email', 'cold-email'),
    ('cold-calling', 'cold-calling'),
    ('coldcalling', 'cold-calling'),
    ('cold calling', 'cold-calling'),
    ('demo-delivery', 'demo-delivery'),
    ('demodelivery', 'demo-delivery'),
    ('demo delivery', 'demo-delivery'),
    ('contract-review-support', 'contract-review-support'),
    ('contractreviewsupport', 'contract-review-support'),
    ('contract review support', 'contract-review-support'),
    ('renewal-management', 'renewal-management'),
    ('renewalmanagement', 'renewal-management'),
    ('renewal management', 'renewal-management'),
    ('figma', 'figma'),
    ('wireframing', 'wireframing'),
    ('prototyping', 'prototyping'),
    ('user-research', 'user-research'),
    ('userresearch', 'user-research'),
    ('user research', 'user-research'),
    ('usability-testing', 'usability-testing'),
    ('usabilitytesting', 'usability-testing'),
    ('usability testing', 'usability-testing'),
    ('interaction-design', 'interaction-design'),
    ('interactiondesign', 'interaction-design'),
    ('interaction design', 'interaction-design'),
    ('information-architecture', 'information-architecture'),
    ('informationarchitecture', 'information-architecture'),
    ('information architecture', 'information-architecture'),
    ('visual-design', 'visual-design'),
    ('visualdesign', 'visual-design'),
    ('visual design', 'visual-design'),
    ('design-systems', 'design-systems'),
    ('designsystems', 'design-systems'),
    ('design systems', 'design-systems'),
    ('accessibility-wcag', 'accessibility-wcag'),
    ('accessibilitywcag', 'accessibility-wcag'),
    ('accessibility (wcag)', 'accessibility-wcag'),
    ('wcag', 'accessibility-wcag'),
    ('accessibility', 'accessibility-wcag'),
    ('adobe-photoshop', 'adobe-photoshop'),
    ('adobephotoshop', 'adobe-photoshop'),
    ('adobe photoshop', 'adobe-photoshop'),
    ('adobe-illustrator', 'adobe-illustrator'),
    ('adobeillustrator', 'adobe-illustrator'),
    ('adobe illustrator', 'adobe-illustrator'),
    ('canva', 'canva'),
    ('typography', 'typography'),
    ('brand-identity', 'brand-identity'),
    ('brandidentity', 'brand-identity'),
    ('brand identity', 'brand-identity'),
    ('motion-design-basics', 'motion-design-basics'),
    ('motiondesignbasics', 'motion-design-basics'),
    ('motion design basics', 'motion-design-basics'),
    ('journey-mapping', 'journey-mapping'),
    ('journeymapping', 'journey-mapping'),
    ('journey mapping', 'journey-mapping'),
    ('persona-development', 'persona-development'),
    ('personadevelopment', 'persona-development'),
    ('persona development', 'persona-development'),
    ('healthcare-administration', 'healthcare-administration'),
    ('healthcareadministration', 'healthcare-administration'),
    ('healthcare administration', 'healthcare-administration'),
    ('medical-billing', 'medical-billing'),
    ('medicalbilling', 'medical-billing'),
    ('medical billing', 'medical-billing'),
    ('medical-coding-basics', 'medical-coding-basics'),
    ('medicalcodingbasics', 'medical-coding-basics'),
    ('medical coding basics', 'medical-coding-basics'),
    ('hipaa-compliance', 'hipaa-compliance'),
    ('hipaacompliance', 'hipaa-compliance'),
    ('hipaa compliance', 'hipaa-compliance'),
    ('electronic-health-records', 'electronic-health-records'),
    ('electronichealthrecords', 'electronic-health-records'),
    ('electronic health records', 'electronic-health-records'),
    ('patient-scheduling', 'patient-scheduling'),
    ('patientscheduling', 'patient-scheduling'),
    ('patient scheduling', 'patient-scheduling'),
    ('revenue-cycle-management', 'revenue-cycle-management'),
    ('revenuecyclemanagement', 'revenue-cycle-management'),
    ('revenue cycle management', 'revenue-cycle-management'),
    ('clinical-documentation', 'clinical-documentation'),
    ('clinicaldocumentation', 'clinical-documentation'),
    ('clinical documentation', 'clinical-documentation'),
    ('insurance-verification', 'insurance-verification'),
    ('insuranceverification', 'insurance-verification'),
    ('insurance verification', 'insurance-verification'),
    ('healthcare-data-entry', 'healthcare-data-entry'),
    ('healthcaredataentry', 'healthcare-data-entry'),
    ('healthcare data entry', 'healthcare-data-entry'),
    ('care-coordination', 'care-coordination'),
    ('carecoordination', 'care-coordination'),
    ('care coordination', 'care-coordination'),
    ('prior-authorization', 'prior-authorization'),
    ('priorauthorization', 'prior-authorization'),
    ('prior authorization', 'prior-authorization'),
    ('construction-management', 'construction-management'),
    ('constructionmanagement', 'construction-management'),
    ('construction management', 'construction-management'),
    ('blueprint-reading', 'blueprint-reading'),
    ('blueprintreading', 'blueprint-reading'),
    ('blueprint reading', 'blueprint-reading'),
    ('cost-estimation', 'cost-estimation'),
    ('costestimation', 'cost-estimation'),
    ('cost estimation', 'cost-estimation'),
    ('bid-coordination', 'bid-coordination'),
    ('bidcoordination', 'bid-coordination'),
    ('bid coordination', 'bid-coordination'),
    ('subcontractor-coordination', 'subcontractor-coordination'),
    ('subcontractorcoordination', 'subcontractor-coordination'),
    ('subcontractor coordination', 'subcontractor-coordination'),
    ('site-safety-basics', 'site-safety-basics'),
    ('sitesafetybasics', 'site-safety-basics'),
    ('site safety basics', 'site-safety-basics'),
    ('osha-basics', 'osha-basics'),
    ('oshabasics', 'osha-basics'),
    ('osha basics', 'osha-basics'),
    ('scheduling-construction', 'scheduling-construction'),
    ('schedulingconstruction', 'scheduling-construction'),
    ('scheduling (construction)', 'scheduling-construction'),
    ('rfi-management', 'rfi-management'),
    ('rfimanagement', 'rfi-management'),
    ('rfi management', 'rfi-management'),
    ('change-order-management', 'change-order-management'),
    ('changeordermanagement', 'change-order-management'),
    ('change order management', 'change-order-management'),
    ('construction-procurement', 'construction-procurement'),
    ('constructionprocurement', 'construction-procurement'),
    ('construction procurement', 'construction-procurement'),
    ('field-reporting', 'field-reporting'),
    ('fieldreporting', 'field-reporting'),
    ('field reporting', 'field-reporting'),
    ('hospitality-operations', 'hospitality-operations'),
    ('hospitalityoperations', 'hospitality-operations'),
    ('hospitality operations', 'hospitality-operations'),
    ('front-desk-operations', 'front-desk-operations'),
    ('frontdeskoperations', 'front-desk-operations'),
    ('front desk operations', 'front-desk-operations'),
    ('guest-services', 'guest-services'),
    ('guestservices', 'guest-services'),
    ('guest services', 'guest-services'),
    ('reservation-management', 'reservation-management'),
    ('reservationmanagement', 'reservation-management'),
    ('reservation management', 'reservation-management'),
    ('event-coordination', 'event-coordination'),
    ('eventcoordination', 'event-coordination'),
    ('event coordination', 'event-coordination'),
    ('food-and-beverage-operations', 'food-and-beverage-operations'),
    ('foodandbeverageoperations', 'food-and-beverage-operations'),
    ('food and beverage operations', 'food-and-beverage-operations'),
    ('housekeeping-coordination', 'housekeeping-coordination'),
    ('housekeepingcoordination', 'housekeeping-coordination'),
    ('housekeeping coordination', 'housekeeping-coordination'),
    ('revenue-management-hospitality', 'revenue-management-hospitality'),
    ('revenuemanagementhospitality', 'revenue-management-hospitality'),
    ('revenue management (hospitality)', 'revenue-management-hospitality'),
    ('pos-systems', 'pos-systems'),
    ('possystems', 'pos-systems'),
    ('pos systems', 'pos-systems'),
    ('customer-recovery', 'customer-recovery'),
    ('customerrecovery', 'customer-recovery'),
    ('customer recovery', 'customer-recovery'),
    ('communication', 'communication'),
    ('teamwork', 'teamwork'),
    ('leadership', 'leadership'),
    ('customer-service', 'customer-service'),
    ('customerservice', 'customer-service'),
    ('customer service', 'customer-service'),
    ('adaptability', 'adaptability'),
    ('critical-thinking', 'critical-thinking'),
    ('criticalthinking', 'critical-thinking'),
    ('critical thinking', 'critical-thinking'),
    ('attention-to-detail', 'attention-to-detail'),
    ('attentiontodetail', 'attention-to-detail'),
    ('attention to detail', 'attention-to-detail'),
    ('organization', 'organization'),
    ('accountability', 'accountability'),
    ('initiative', 'initiative'),
    ('conflict-resolution', 'conflict-resolution'),
    ('conflictresolution', 'conflict-resolution'),
    ('conflict resolution', 'conflict-resolution'),
    ('coaching', 'coaching'),
    ('mentoring', 'mentoring'),
    ('emotional-intelligence', 'emotional-intelligence'),
    ('emotionalintelligence', 'emotional-intelligence'),
    ('emotional intelligence', 'emotional-intelligence'),
    ('multitasking', 'multitasking'),
    ('professional-writing', 'professional-writing'),
    ('professionalwriting', 'professional-writing'),
    ('professional writing', 'professional-writing'),
    ('presentation-delivery', 'presentation-delivery'),
    ('presentationdelivery', 'presentation-delivery'),
    ('presentation delivery', 'presentation-delivery'),
    ('collaboration', 'collaboration'),
    ('analytical-thinking', 'analytical-thinking'),
    ('analyticalthinking', 'analytical-thinking'),
    ('analytical thinking', 'analytical-thinking'),
    ('reliability', 'reliability')
), resolved as (
  select am.alias, s.id as skill_id
  from alias_map am
  join public.skills s on s.slug = am.slug
)
insert into public.skill_aliases (alias, skill_id)
select alias, skill_id
from resolved
on conflict (alias) do update
set skill_id = excluded.skill_id;

with alias_map(alias, slug) as (
  values
    ('microsoft-excel', 'microsoft-excel'),
    ('microsoftexcel', 'microsoft-excel'),
    ('microsoft excel', 'microsoft-excel'),
    ('excel', 'microsoft-excel'),
    ('ms excel', 'microsoft-excel'),
    ('excel advanced', 'microsoft-excel'),
    ('excel pivot tables', 'excel-pivot-tables'),
    ('microsoft-powerpoint', 'microsoft-powerpoint'),
    ('microsoftpowerpoint', 'microsoft-powerpoint'),
    ('microsoft powerpoint', 'microsoft-powerpoint'),
    ('powerpoint', 'microsoft-powerpoint'),
    ('ms powerpoint', 'microsoft-powerpoint'),
    ('microsoft-word', 'microsoft-word'),
    ('microsoftword', 'microsoft-word'),
    ('microsoft word', 'microsoft-word'),
    ('business-writing', 'business-writing'),
    ('businesswriting', 'business-writing'),
    ('business writing', 'business-writing'),
    ('business-communication', 'business-communication'),
    ('businesscommunication', 'business-communication'),
    ('business communication', 'business-communication'),
    ('stakeholder-management', 'stakeholder-management'),
    ('stakeholdermanagement', 'stakeholder-management'),
    ('stakeholder management', 'stakeholder-management'),
    ('project-coordination', 'project-coordination'),
    ('projectcoordination', 'project-coordination'),
    ('project coordination', 'project-coordination'),
    ('strategic-planning', 'strategic-planning'),
    ('strategicplanning', 'strategic-planning'),
    ('strategic planning', 'strategic-planning'),
    ('business-analysis', 'business-analysis'),
    ('businessanalysis', 'business-analysis'),
    ('business analysis', 'business-analysis'),
    ('requirements-gathering', 'requirements-gathering'),
    ('requirementsgathering', 'requirements-gathering'),
    ('requirements gathering', 'requirements-gathering'),
    ('process-documentation', 'process-documentation'),
    ('processdocumentation', 'process-documentation'),
    ('process documentation', 'process-documentation'),
    ('change-management', 'change-management'),
    ('changemanagement', 'change-management'),
    ('change management', 'change-management'),
    ('client-relations', 'client-relations'),
    ('clientrelations', 'client-relations'),
    ('client relations', 'client-relations'),
    ('vendor-management', 'vendor-management'),
    ('vendormanagement', 'vendor-management'),
    ('vendor management', 'vendor-management'),
    ('negotiation', 'negotiation'),
    ('meeting-facilitation', 'meeting-facilitation'),
    ('meetingfacilitation', 'meeting-facilitation'),
    ('meeting facilitation', 'meeting-facilitation'),
    ('presentation-skills', 'presentation-skills'),
    ('presentationskills', 'presentation-skills'),
    ('presentation skills', 'presentation-skills'),
    ('public-speaking', 'public-speaking'),
    ('publicspeaking', 'public-speaking'),
    ('public speaking', 'public-speaking'),
    ('time-management', 'time-management'),
    ('timemanagement', 'time-management'),
    ('time management', 'time-management'),
    ('cross-functional-collaboration', 'cross-functional-collaboration'),
    ('crossfunctionalcollaboration', 'cross-functional-collaboration'),
    ('cross-functional collaboration', 'cross-functional-collaboration'),
    ('decision-making', 'decision-making'),
    ('decisionmaking', 'decision-making'),
    ('decision making', 'decision-making'),
    ('problem-solving', 'problem-solving'),
    ('problemsolving', 'problem-solving'),
    ('problem solving', 'problem-solving'),
    ('professional-etiquette', 'professional-etiquette'),
    ('professionaletiquette', 'professional-etiquette'),
    ('professional etiquette', 'professional-etiquette'),
    ('financial-modeling', 'financial-modeling'),
    ('financialmodeling', 'financial-modeling'),
    ('financial modeling', 'financial-modeling'),
    ('valuation', 'valuation'),
    ('financial-statement-analysis', 'financial-statement-analysis'),
    ('financialstatementanalysis', 'financial-statement-analysis'),
    ('financial statement analysis', 'financial-statement-analysis'),
    ('gaap', 'gaap'),
    ('budgeting', 'budgeting'),
    ('forecasting', 'forecasting'),
    ('variance-analysis', 'variance-analysis'),
    ('varianceanalysis', 'variance-analysis'),
    ('variance analysis', 'variance-analysis'),
    ('cash-flow-analysis', 'cash-flow-analysis'),
    ('cashflowanalysis', 'cash-flow-analysis'),
    ('cash flow analysis', 'cash-flow-analysis'),
    ('corporate-finance', 'corporate-finance'),
    ('corporatefinance', 'corporate-finance'),
    ('corporate finance', 'corporate-finance'),
    ('investment-analysis', 'investment-analysis'),
    ('investmentanalysis', 'investment-analysis'),
    ('investment analysis', 'investment-analysis'),
    ('equity-research', 'equity-research'),
    ('equityresearch', 'equity-research'),
    ('equity research', 'equity-research'),
    ('credit-analysis', 'credit-analysis'),
    ('creditanalysis', 'credit-analysis'),
    ('credit analysis', 'credit-analysis'),
    ('mergers-and-acquisitions', 'mergers-and-acquisitions'),
    ('mergersandacquisitions', 'mergers-and-acquisitions'),
    ('mergers and acquisitions', 'mergers-and-acquisitions'),
    ('due-diligence', 'due-diligence'),
    ('duediligence', 'due-diligence'),
    ('due diligence', 'due-diligence'),
    ('capital-markets', 'capital-markets'),
    ('capitalmarkets', 'capital-markets'),
    ('capital markets', 'capital-markets'),
    ('portfolio-analysis', 'portfolio-analysis'),
    ('portfolioanalysis', 'portfolio-analysis'),
    ('portfolio analysis', 'portfolio-analysis'),
    ('risk-management', 'risk-management'),
    ('riskmanagement', 'risk-management'),
    ('risk management', 'risk-management'),
    ('treasury-operations', 'treasury-operations'),
    ('treasuryoperations', 'treasury-operations'),
    ('treasury operations', 'treasury-operations'),
    ('quickbooks', 'quickbooks'),
    ('accounts-payable', 'accounts-payable'),
    ('accountspayable', 'accounts-payable'),
    ('accounts payable', 'accounts-payable'),
    ('accounts-receivable', 'accounts-receivable'),
    ('accountsreceivable', 'accounts-receivable'),
    ('accounts receivable', 'accounts-receivable'),
    ('reconciliations', 'reconciliations'),
    ('audit-support', 'audit-support'),
    ('auditsupport', 'audit-support'),
    ('audit support', 'audit-support'),
    ('tax-preparation', 'tax-preparation'),
    ('taxpreparation', 'tax-preparation'),
    ('tax preparation', 'tax-preparation'),
    ('payroll-processing', 'payroll-processing'),
    ('payrollprocessing', 'payroll-processing'),
    ('payroll processing', 'payroll-processing'),
    ('internal-controls', 'internal-controls'),
    ('internalcontrols', 'internal-controls'),
    ('internal controls', 'internal-controls'),
    ('cost-accounting', 'cost-accounting'),
    ('costaccounting', 'cost-accounting'),
    ('cost accounting', 'cost-accounting'),
    ('managerial-accounting', 'managerial-accounting'),
    ('managerialaccounting', 'managerial-accounting'),
    ('managerial accounting', 'managerial-accounting'),
    ('fund-accounting', 'fund-accounting'),
    ('fundaccounting', 'fund-accounting'),
    ('fund accounting', 'fund-accounting'),
    ('revenue-recognition', 'revenue-recognition'),
    ('revenuerecognition', 'revenue-recognition'),
    ('revenue recognition', 'revenue-recognition'),
    ('sql', 'sql'),
    ('postgresql', 'postgresql'),
    ('mysql', 'mysql'),
    ('sqlite', 'sqlite'),
    ('data-cleaning', 'data-cleaning'),
    ('datacleaning', 'data-cleaning'),
    ('data cleaning', 'data-cleaning'),
    ('data-wrangling', 'data-wrangling'),
    ('datawrangling', 'data-wrangling'),
    ('data wrangling', 'data-wrangling'),
    ('exploratory-data-analysis', 'exploratory-data-analysis'),
    ('exploratorydataanalysis', 'exploratory-data-analysis'),
    ('exploratory data analysis', 'exploratory-data-analysis'),
    ('statistical-analysis', 'statistical-analysis'),
    ('statisticalanalysis', 'statistical-analysis'),
    ('statistical analysis', 'statistical-analysis'),
    ('a-b-testing', 'a-b-testing'),
    ('abtesting', 'a-b-testing'),
    ('a/b testing', 'a-b-testing'),
    ('ab testing', 'a-b-testing'),
    ('a b testing', 'a-b-testing'),
    ('hypothesis-testing', 'hypothesis-testing'),
    ('hypothesistesting', 'hypothesis-testing'),
    ('hypothesis testing', 'hypothesis-testing'),
    ('regression-analysis', 'regression-analysis'),
    ('regressionanalysis', 'regression-analysis'),
    ('regression analysis', 'regression-analysis'),
    ('data-visualization', 'data-visualization'),
    ('datavisualization', 'data-visualization'),
    ('data visualization', 'data-visualization'),
    ('dashboarding', 'dashboarding'),
    ('tableau', 'tableau'),
    ('power-bi', 'power-bi'),
    ('powerbi', 'power-bi'),
    ('power bi', 'power-bi'),
    ('looker-studio', 'looker-studio'),
    ('lookerstudio', 'looker-studio'),
    ('looker studio', 'looker-studio'),
    ('excel-pivot-tables', 'excel-pivot-tables'),
    ('excelpivottables', 'excel-pivot-tables'),
    ('excel-xlookup', 'excel-xlookup'),
    ('excelxlookup', 'excel-xlookup'),
    ('excel xlookup', 'excel-xlookup'),
    ('xlookup', 'excel-xlookup'),
    ('excel-vlookup', 'excel-vlookup'),
    ('excelvlookup', 'excel-vlookup'),
    ('excel vlookup', 'excel-vlookup'),
    ('vlookup', 'excel-vlookup'),
    ('google-sheets', 'google-sheets'),
    ('googlesheets', 'google-sheets'),
    ('google sheets', 'google-sheets'),
    ('g sheets', 'google-sheets'),
    ('python-for-analytics', 'python-for-analytics'),
    ('pythonforanalytics', 'python-for-analytics'),
    ('python for analytics', 'python-for-analytics'),
    ('r-programming', 'r-programming'),
    ('rprogramming', 'r-programming'),
    ('r programming', 'r-programming'),
    ('jupyter', 'jupyter'),
    ('pandas', 'pandas'),
    ('numpy', 'numpy'),
    ('etl', 'etl'),
    ('data-modeling', 'data-modeling'),
    ('datamodeling', 'data-modeling'),
    ('data modeling', 'data-modeling'),
    ('data-governance', 'data-governance'),
    ('datagovernance', 'data-governance'),
    ('data governance', 'data-governance'),
    ('data-quality', 'data-quality'),
    ('dataquality', 'data-quality'),
    ('data quality', 'data-quality'),
    ('business-intelligence', 'business-intelligence'),
    ('businessintelligence', 'business-intelligence'),
    ('business intelligence', 'business-intelligence'),
    ('javascript', 'javascript'),
    ('js', 'javascript'),
    ('typescript', 'typescript'),
    ('ts', 'typescript'),
    ('react', 'react'),
    ('next-js', 'next-js'),
    ('nextjs', 'next-js'),
    ('next.js', 'next-js'),
    ('next js', 'next-js'),
    ('node-js', 'node-js'),
    ('nodejs', 'node-js'),
    ('node.js', 'node-js'),
    ('node js', 'node-js'),
    ('express-js', 'express-js'),
    ('expressjs', 'express-js'),
    ('express.js', 'express-js'),
    ('rest-apis', 'rest-apis'),
    ('restapis', 'rest-apis'),
    ('rest apis', 'rest-apis'),
    ('rest api', 'rest-apis'),
    ('restful api', 'rest-apis'),
    ('apis', 'rest-apis'),
    ('graphql', 'graphql'),
    ('html', 'html'),
    ('css', 'css'),
    ('tailwind-css', 'tailwind-css'),
    ('tailwindcss', 'tailwind-css'),
    ('tailwind css', 'tailwind-css'),
    ('sass', 'sass'),
    ('git', 'git'),
    ('github', 'github'),
    ('ci-cd', 'ci-cd'),
    ('cicd', 'ci-cd'),
    ('ci/cd', 'ci-cd'),
    ('continuous integration', 'ci-cd'),
    ('continuous delivery', 'ci-cd'),
    ('unit-testing', 'unit-testing'),
    ('unittesting', 'unit-testing'),
    ('unit testing', 'unit-testing'),
    ('integration-testing', 'integration-testing'),
    ('integrationtesting', 'integration-testing'),
    ('integration testing', 'integration-testing'),
    ('jest', 'jest'),
    ('playwright', 'playwright'),
    ('docker', 'docker'),
    ('kubernetes-basics', 'kubernetes-basics'),
    ('kubernetesbasics', 'kubernetes-basics'),
    ('kubernetes basics', 'kubernetes-basics'),
    ('linux', 'linux'),
    ('bash', 'bash'),
    ('json', 'json'),
    ('oauth', 'oauth'),
    ('authentication', 'authentication'),
    ('authorization', 'authorization'),
    ('api-integration', 'api-integration'),
    ('apiintegration', 'api-integration'),
    ('api integration', 'api-integration'),
    ('system-design', 'system-design'),
    ('systemdesign', 'system-design'),
    ('system design', 'system-design'),
    ('agile-development', 'agile-development'),
    ('agiledevelopment', 'agile-development'),
    ('agile development', 'agile-development'),
    ('aws-basics', 'aws-basics'),
    ('awsbasics', 'aws-basics'),
    ('aws basics', 'aws-basics'),
    ('amazon-s3', 'amazon-s3'),
    ('amazons3', 'amazon-s3'),
    ('amazon s3', 'amazon-s3'),
    ('aws-lambda', 'aws-lambda'),
    ('awslambda', 'aws-lambda'),
    ('aws lambda', 'aws-lambda'),
    ('cloudwatch', 'cloudwatch'),
    ('google-cloud-basics', 'google-cloud-basics'),
    ('googlecloudbasics', 'google-cloud-basics'),
    ('google cloud basics', 'google-cloud-basics'),
    ('azure-basics', 'azure-basics'),
    ('azurebasics', 'azure-basics'),
    ('azure basics', 'azure-basics'),
    ('vercel-deployment', 'vercel-deployment'),
    ('verceldeployment', 'vercel-deployment'),
    ('vercel deployment', 'vercel-deployment'),
    ('netlify-deployment', 'netlify-deployment'),
    ('netlifydeployment', 'netlify-deployment'),
    ('netlify deployment', 'netlify-deployment'),
    ('infrastructure-as-code', 'infrastructure-as-code'),
    ('infrastructureascode', 'infrastructure-as-code'),
    ('infrastructure as code', 'infrastructure-as-code'),
    ('terraform-basics', 'terraform-basics'),
    ('terraformbasics', 'terraform-basics'),
    ('terraform basics', 'terraform-basics'),
    ('serverless-basics', 'serverless-basics'),
    ('serverlessbasics', 'serverless-basics'),
    ('serverless basics', 'serverless-basics'),
    ('cdn-fundamentals', 'cdn-fundamentals'),
    ('cdnfundamentals', 'cdn-fundamentals'),
    ('cdn fundamentals', 'cdn-fundamentals'),
    ('cloud-security-basics', 'cloud-security-basics'),
    ('cloudsecuritybasics', 'cloud-security-basics'),
    ('cloud security basics', 'cloud-security-basics'),
    ('monitoring-and-alerting', 'monitoring-and-alerting'),
    ('monitoringandalerting', 'monitoring-and-alerting'),
    ('monitoring and alerting', 'monitoring-and-alerting'),
    ('incident-response', 'incident-response'),
    ('incidentresponse', 'incident-response'),
    ('incident response', 'incident-response'),
    ('seo', 'seo'),
    ('sem', 'sem'),
    ('google-ads', 'google-ads'),
    ('googleads', 'google-ads'),
    ('google ads', 'google-ads'),
    ('meta-ads', 'meta-ads'),
    ('metaads', 'meta-ads'),
    ('meta ads', 'meta-ads'),
    ('linkedin-ads', 'linkedin-ads'),
    ('linkedinads', 'linkedin-ads'),
    ('linkedin ads', 'linkedin-ads'),
    ('email-marketing', 'email-marketing'),
    ('emailmarketing', 'email-marketing'),
    ('email marketing', 'email-marketing'),
    ('lifecycle-marketing', 'lifecycle-marketing'),
    ('lifecyclemarketing', 'lifecycle-marketing'),
    ('lifecycle marketing', 'lifecycle-marketing'),
    ('marketing-automation', 'marketing-automation'),
    ('marketingautomation', 'marketing-automation'),
    ('marketing automation', 'marketing-automation'),
    ('hubspot', 'hubspot'),
    ('salesforce-crm', 'salesforce-crm'),
    ('salesforcecrm', 'salesforce-crm'),
    ('salesforce crm', 'salesforce-crm'),
    ('salesforce', 'salesforce-crm'),
    ('content-marketing', 'content-marketing'),
    ('contentmarketing', 'content-marketing'),
    ('content marketing', 'content-marketing'),
    ('copywriting', 'copywriting'),
    ('social-media-management', 'social-media-management'),
    ('socialmediamanagement', 'social-media-management'),
    ('social media management', 'social-media-management'),
    ('influencer-marketing', 'influencer-marketing'),
    ('influencermarketing', 'influencer-marketing'),
    ('influencer marketing', 'influencer-marketing'),
    ('brand-strategy', 'brand-strategy'),
    ('brandstrategy', 'brand-strategy'),
    ('brand strategy', 'brand-strategy'),
    ('campaign-planning', 'campaign-planning'),
    ('campaignplanning', 'campaign-planning'),
    ('campaign planning', 'campaign-planning'),
    ('market-research', 'market-research'),
    ('marketresearch', 'market-research'),
    ('market research', 'market-research'),
    ('competitive-analysis', 'competitive-analysis'),
    ('competitiveanalysis', 'competitive-analysis'),
    ('competitive analysis', 'competitive-analysis'),
    ('conversion-rate-optimization', 'conversion-rate-optimization'),
    ('conversionrateoptimization', 'conversion-rate-optimization'),
    ('conversion rate optimization', 'conversion-rate-optimization'),
    ('web-analytics', 'web-analytics'),
    ('webanalytics', 'web-analytics'),
    ('web analytics', 'web-analytics'),
    ('google-analytics', 'google-analytics'),
    ('googleanalytics', 'google-analytics'),
    ('google analytics', 'google-analytics'),
    ('a-b-creative-testing', 'a-b-creative-testing'),
    ('abcreativetesting', 'a-b-creative-testing'),
    ('a/b creative testing', 'a-b-creative-testing'),
    ('creative ab testing', 'a-b-creative-testing'),
    ('landing-page-optimization', 'landing-page-optimization'),
    ('landingpageoptimization', 'landing-page-optimization'),
    ('landing page optimization', 'landing-page-optimization'),
    ('pr-outreach', 'pr-outreach'),
    ('proutreach', 'pr-outreach'),
    ('pr outreach', 'pr-outreach'),
    ('event-marketing', 'event-marketing'),
    ('eventmarketing', 'event-marketing'),
    ('event marketing', 'event-marketing'),
    ('project-management', 'project-management'),
    ('projectmanagement', 'project-management'),
    ('project management', 'project-management'),
    ('program-management', 'program-management'),
    ('programmanagement', 'program-management'),
    ('program management', 'program-management'),
    ('operations-analysis', 'operations-analysis'),
    ('operationsanalysis', 'operations-analysis'),
    ('operations analysis', 'operations-analysis'),
    ('process-improvement', 'process-improvement'),
    ('processimprovement', 'process-improvement'),
    ('process improvement', 'process-improvement'),
    ('lean', 'lean'),
    ('six-sigma', 'six-sigma'),
    ('sixsigma', 'six-sigma'),
    ('six sigma', 'six-sigma'),
    ('kaizen', 'kaizen'),
    ('sop-development', 'sop-development'),
    ('sopdevelopment', 'sop-development'),
    ('sop development', 'sop-development'),
    ('capacity-planning', 'capacity-planning'),
    ('capacityplanning', 'capacity-planning'),
    ('capacity planning', 'capacity-planning'),
    ('supply-chain-fundamentals', 'supply-chain-fundamentals'),
    ('supplychainfundamentals', 'supply-chain-fundamentals'),
    ('supply chain fundamentals', 'supply-chain-fundamentals'),
    ('procurement', 'procurement'),
    ('inventory-management', 'inventory-management'),
    ('inventorymanagement', 'inventory-management'),
    ('inventory management', 'inventory-management'),
    ('logistics-coordination', 'logistics-coordination'),
    ('logisticscoordination', 'logistics-coordination'),
    ('logistics coordination', 'logistics-coordination'),
    ('quality-assurance', 'quality-assurance'),
    ('qualityassurance', 'quality-assurance'),
    ('quality assurance', 'quality-assurance'),
    ('kpi-tracking', 'kpi-tracking'),
    ('kpitracking', 'kpi-tracking'),
    ('kpi tracking', 'kpi-tracking'),
    ('okr-planning', 'okr-planning'),
    ('okrplanning', 'okr-planning'),
    ('okr planning', 'okr-planning'),
    ('resource-planning', 'resource-planning'),
    ('resourceplanning', 'resource-planning'),
    ('resource planning', 'resource-planning'),
    ('scheduling', 'scheduling'),
    ('workforce-planning', 'workforce-planning'),
    ('workforceplanning', 'workforce-planning'),
    ('workforce planning', 'workforce-planning'),
    ('risk-register-management', 'risk-register-management'),
    ('riskregistermanagement', 'risk-register-management'),
    ('risk register management', 'risk-register-management'),
    ('compliance-operations', 'compliance-operations'),
    ('complianceoperations', 'compliance-operations'),
    ('compliance operations', 'compliance-operations'),
    ('documentation-control', 'documentation-control'),
    ('documentationcontrol', 'documentation-control'),
    ('documentation control', 'documentation-control'),
    ('prospecting', 'prospecting'),
    ('lead-qualification', 'lead-qualification'),
    ('leadqualification', 'lead-qualification'),
    ('lead qualification', 'lead-qualification'),
    ('pipeline-management', 'pipeline-management'),
    ('pipelinemanagement', 'pipeline-management'),
    ('pipeline management', 'pipeline-management'),
    ('crm-hygiene', 'crm-hygiene'),
    ('crmhygiene', 'crm-hygiene'),
    ('crm hygiene', 'crm-hygiene'),
    ('discovery-calls', 'discovery-calls'),
    ('discoverycalls', 'discovery-calls'),
    ('discovery calls', 'discovery-calls'),
    ('objection-handling', 'objection-handling'),
    ('objectionhandling', 'objection-handling'),
    ('objection handling', 'objection-handling'),
    ('negotiation-for-sales', 'negotiation-for-sales'),
    ('negotiationforsales', 'negotiation-for-sales'),
    ('negotiation for sales', 'negotiation-for-sales'),
    ('account-management', 'account-management'),
    ('accountmanagement', 'account-management'),
    ('account management', 'account-management'),
    ('customer-success', 'customer-success'),
    ('customersuccess', 'customer-success'),
    ('customer success', 'customer-success'),
    ('upselling', 'upselling'),
    ('cross-selling', 'cross-selling'),
    ('crossselling', 'cross-selling'),
    ('sales-forecasting', 'sales-forecasting'),
    ('salesforecasting', 'sales-forecasting'),
    ('sales forecasting', 'sales-forecasting'),
    ('territory-planning', 'territory-planning'),
    ('territoryplanning', 'territory-planning'),
    ('territory planning', 'territory-planning'),
    ('cold-email', 'cold-email'),
    ('coldemail', 'cold-email'),
    ('cold email', 'cold-email'),
    ('cold-calling', 'cold-calling'),
    ('coldcalling', 'cold-calling'),
    ('cold calling', 'cold-calling'),
    ('demo-delivery', 'demo-delivery'),
    ('demodelivery', 'demo-delivery'),
    ('demo delivery', 'demo-delivery'),
    ('contract-review-support', 'contract-review-support'),
    ('contractreviewsupport', 'contract-review-support'),
    ('contract review support', 'contract-review-support'),
    ('renewal-management', 'renewal-management'),
    ('renewalmanagement', 'renewal-management'),
    ('renewal management', 'renewal-management'),
    ('figma', 'figma'),
    ('wireframing', 'wireframing'),
    ('prototyping', 'prototyping'),
    ('user-research', 'user-research'),
    ('userresearch', 'user-research'),
    ('user research', 'user-research'),
    ('usability-testing', 'usability-testing'),
    ('usabilitytesting', 'usability-testing'),
    ('usability testing', 'usability-testing'),
    ('interaction-design', 'interaction-design'),
    ('interactiondesign', 'interaction-design'),
    ('interaction design', 'interaction-design'),
    ('information-architecture', 'information-architecture'),
    ('informationarchitecture', 'information-architecture'),
    ('information architecture', 'information-architecture'),
    ('visual-design', 'visual-design'),
    ('visualdesign', 'visual-design'),
    ('visual design', 'visual-design'),
    ('design-systems', 'design-systems'),
    ('designsystems', 'design-systems'),
    ('design systems', 'design-systems'),
    ('accessibility-wcag', 'accessibility-wcag'),
    ('accessibilitywcag', 'accessibility-wcag'),
    ('accessibility (wcag)', 'accessibility-wcag'),
    ('wcag', 'accessibility-wcag'),
    ('accessibility', 'accessibility-wcag'),
    ('adobe-photoshop', 'adobe-photoshop'),
    ('adobephotoshop', 'adobe-photoshop'),
    ('adobe photoshop', 'adobe-photoshop'),
    ('adobe-illustrator', 'adobe-illustrator'),
    ('adobeillustrator', 'adobe-illustrator'),
    ('adobe illustrator', 'adobe-illustrator'),
    ('canva', 'canva'),
    ('typography', 'typography'),
    ('brand-identity', 'brand-identity'),
    ('brandidentity', 'brand-identity'),
    ('brand identity', 'brand-identity'),
    ('motion-design-basics', 'motion-design-basics'),
    ('motiondesignbasics', 'motion-design-basics'),
    ('motion design basics', 'motion-design-basics'),
    ('journey-mapping', 'journey-mapping'),
    ('journeymapping', 'journey-mapping'),
    ('journey mapping', 'journey-mapping'),
    ('persona-development', 'persona-development'),
    ('personadevelopment', 'persona-development'),
    ('persona development', 'persona-development'),
    ('healthcare-administration', 'healthcare-administration'),
    ('healthcareadministration', 'healthcare-administration'),
    ('healthcare administration', 'healthcare-administration'),
    ('medical-billing', 'medical-billing'),
    ('medicalbilling', 'medical-billing'),
    ('medical billing', 'medical-billing'),
    ('medical-coding-basics', 'medical-coding-basics'),
    ('medicalcodingbasics', 'medical-coding-basics'),
    ('medical coding basics', 'medical-coding-basics'),
    ('hipaa-compliance', 'hipaa-compliance'),
    ('hipaacompliance', 'hipaa-compliance'),
    ('hipaa compliance', 'hipaa-compliance'),
    ('electronic-health-records', 'electronic-health-records'),
    ('electronichealthrecords', 'electronic-health-records'),
    ('electronic health records', 'electronic-health-records'),
    ('patient-scheduling', 'patient-scheduling'),
    ('patientscheduling', 'patient-scheduling'),
    ('patient scheduling', 'patient-scheduling'),
    ('revenue-cycle-management', 'revenue-cycle-management'),
    ('revenuecyclemanagement', 'revenue-cycle-management'),
    ('revenue cycle management', 'revenue-cycle-management'),
    ('clinical-documentation', 'clinical-documentation'),
    ('clinicaldocumentation', 'clinical-documentation'),
    ('clinical documentation', 'clinical-documentation'),
    ('insurance-verification', 'insurance-verification'),
    ('insuranceverification', 'insurance-verification'),
    ('insurance verification', 'insurance-verification'),
    ('healthcare-data-entry', 'healthcare-data-entry'),
    ('healthcaredataentry', 'healthcare-data-entry'),
    ('healthcare data entry', 'healthcare-data-entry'),
    ('care-coordination', 'care-coordination'),
    ('carecoordination', 'care-coordination'),
    ('care coordination', 'care-coordination'),
    ('prior-authorization', 'prior-authorization'),
    ('priorauthorization', 'prior-authorization'),
    ('prior authorization', 'prior-authorization'),
    ('construction-management', 'construction-management'),
    ('constructionmanagement', 'construction-management'),
    ('construction management', 'construction-management'),
    ('blueprint-reading', 'blueprint-reading'),
    ('blueprintreading', 'blueprint-reading'),
    ('blueprint reading', 'blueprint-reading'),
    ('cost-estimation', 'cost-estimation'),
    ('costestimation', 'cost-estimation'),
    ('cost estimation', 'cost-estimation'),
    ('bid-coordination', 'bid-coordination'),
    ('bidcoordination', 'bid-coordination'),
    ('bid coordination', 'bid-coordination'),
    ('subcontractor-coordination', 'subcontractor-coordination'),
    ('subcontractorcoordination', 'subcontractor-coordination'),
    ('subcontractor coordination', 'subcontractor-coordination'),
    ('site-safety-basics', 'site-safety-basics'),
    ('sitesafetybasics', 'site-safety-basics'),
    ('site safety basics', 'site-safety-basics'),
    ('osha-basics', 'osha-basics'),
    ('oshabasics', 'osha-basics'),
    ('osha basics', 'osha-basics'),
    ('scheduling-construction', 'scheduling-construction'),
    ('schedulingconstruction', 'scheduling-construction'),
    ('scheduling (construction)', 'scheduling-construction'),
    ('rfi-management', 'rfi-management'),
    ('rfimanagement', 'rfi-management'),
    ('rfi management', 'rfi-management'),
    ('change-order-management', 'change-order-management'),
    ('changeordermanagement', 'change-order-management'),
    ('change order management', 'change-order-management'),
    ('construction-procurement', 'construction-procurement'),
    ('constructionprocurement', 'construction-procurement'),
    ('construction procurement', 'construction-procurement'),
    ('field-reporting', 'field-reporting'),
    ('fieldreporting', 'field-reporting'),
    ('field reporting', 'field-reporting'),
    ('hospitality-operations', 'hospitality-operations'),
    ('hospitalityoperations', 'hospitality-operations'),
    ('hospitality operations', 'hospitality-operations'),
    ('front-desk-operations', 'front-desk-operations'),
    ('frontdeskoperations', 'front-desk-operations'),
    ('front desk operations', 'front-desk-operations'),
    ('guest-services', 'guest-services'),
    ('guestservices', 'guest-services'),
    ('guest services', 'guest-services'),
    ('reservation-management', 'reservation-management'),
    ('reservationmanagement', 'reservation-management'),
    ('reservation management', 'reservation-management'),
    ('event-coordination', 'event-coordination'),
    ('eventcoordination', 'event-coordination'),
    ('event coordination', 'event-coordination'),
    ('food-and-beverage-operations', 'food-and-beverage-operations'),
    ('foodandbeverageoperations', 'food-and-beverage-operations'),
    ('food and beverage operations', 'food-and-beverage-operations'),
    ('housekeeping-coordination', 'housekeeping-coordination'),
    ('housekeepingcoordination', 'housekeeping-coordination'),
    ('housekeeping coordination', 'housekeeping-coordination'),
    ('revenue-management-hospitality', 'revenue-management-hospitality'),
    ('revenuemanagementhospitality', 'revenue-management-hospitality'),
    ('revenue management (hospitality)', 'revenue-management-hospitality'),
    ('pos-systems', 'pos-systems'),
    ('possystems', 'pos-systems'),
    ('pos systems', 'pos-systems'),
    ('customer-recovery', 'customer-recovery'),
    ('customerrecovery', 'customer-recovery'),
    ('customer recovery', 'customer-recovery'),
    ('communication', 'communication'),
    ('teamwork', 'teamwork'),
    ('leadership', 'leadership'),
    ('customer-service', 'customer-service'),
    ('customerservice', 'customer-service'),
    ('customer service', 'customer-service'),
    ('adaptability', 'adaptability'),
    ('critical-thinking', 'critical-thinking'),
    ('criticalthinking', 'critical-thinking'),
    ('critical thinking', 'critical-thinking'),
    ('attention-to-detail', 'attention-to-detail'),
    ('attentiontodetail', 'attention-to-detail'),
    ('attention to detail', 'attention-to-detail'),
    ('organization', 'organization'),
    ('accountability', 'accountability'),
    ('initiative', 'initiative'),
    ('conflict-resolution', 'conflict-resolution'),
    ('conflictresolution', 'conflict-resolution'),
    ('conflict resolution', 'conflict-resolution'),
    ('coaching', 'coaching'),
    ('mentoring', 'mentoring'),
    ('emotional-intelligence', 'emotional-intelligence'),
    ('emotionalintelligence', 'emotional-intelligence'),
    ('emotional intelligence', 'emotional-intelligence'),
    ('multitasking', 'multitasking'),
    ('professional-writing', 'professional-writing'),
    ('professionalwriting', 'professional-writing'),
    ('professional writing', 'professional-writing'),
    ('presentation-delivery', 'presentation-delivery'),
    ('presentationdelivery', 'presentation-delivery'),
    ('presentation delivery', 'presentation-delivery'),
    ('collaboration', 'collaboration'),
    ('analytical-thinking', 'analytical-thinking'),
    ('analyticalthinking', 'analytical-thinking'),
    ('analytical thinking', 'analytical-thinking'),
    ('reliability', 'reliability')
), resolved as (
  select am.alias, s.id as canonical_skill_id
  from alias_map am
  join public.skills s on s.slug = am.slug
)
insert into public.canonical_skill_aliases (alias, canonical_skill_id)
select alias, canonical_skill_id
from resolved
on conflict (alias) do update
set canonical_skill_id = excluded.canonical_skill_id;
